# Generated by Django 3.0.8 on 2020-11-02 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordPlay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synonym',
            name='antonym',
        ),
        migrations.CreateModel(
            name='Antonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antonym', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_words', to='wordPlay.Word')),
            ],
        ),
    ]
