# Generated by Django 3.0.8 on 2020-11-02 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordPlay', '0002_auto_20201102_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='word_originals', to='wordPlay.Word'),
        ),
    ]
