# Generated by Django 3.0.8 on 2020-11-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordPlay', '0004_auto_20201102_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
