# Generated by Django 3.0.8 on 2020-11-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordPlay', '0006_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
