# Generated by Django 3.0.8 on 2020-11-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordPlay', '0007_word_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='like_count',
        ),
        migrations.AddField(
            model_name='quotation',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
