# Generated by Django 3.0.8 on 2020-11-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordPlay', '0008_auto_20201125_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='bookmark_count',
            field=models.IntegerField(default=0),
        ),
    ]
