# Generated by Django 3.0.8 on 2020-11-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordPlay', '0009_word_bookmark_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
