# Generated by Django 3.0.8 on 2020-11-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordPlay', '0011_auto_20201130_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='wordPlay.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
