# Generated by Django 3.0.8 on 2020-11-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordPlay', '0012_auto_20201130_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
