# Generated by Django 3.0.8 on 2020-12-02 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordPlay', '0020_auto_20201202_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
