# Generated by Django 3.0.8 on 2020-12-07 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordPlay', '0021_auto_20201202_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='liked_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='wordPlay.Category'),
        ),
    ]
