# Generated by Django 3.0.8 on 2020-12-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordPlay', '0022_auto_20201207_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='liked_times',
        ),
    ]
