# Generated by Django 3.0.8 on 2020-12-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordPlay', '0023_remove_quotation_liked_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
